// import React from 'react'

const NameContainer = () => {
    return (
        <>
            <p className="nameInfo">Derrick</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">Sam</p>
            <p className="nameInfo">Ryan</p>
            <p className="nameInfo">ZzSniperWolfZz</p>
            <p className="nameInfo">ZzSniperWolfZz</p>
            <p className="nameInfo">ZzSniperWolfZz</p>
        </>
    )
}

export default NameContainer
