// import React from 'react'

const RankContainer = () => {
    return (
        <>
            <p className="nameInfo">1</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">2</p>
            <p className="nameInfo">3</p>
            <p className="nameInfo">4</p>
            <p className="nameInfo">5</p>
            <p className="nameInfo">6</p>
        </>
    )
}

export default RankContainer
