// import React from 'react'

const ScoreContainer = ({scores}) => {
    return (
        <>
            <p className="nameInfo">{scores[0]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{scores[0]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{scores[0]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{scores[0]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{scores[0]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{scores[0]}</p> {/* This will be dynamically generated by server */}
        
        </>
    )
}

export default ScoreContainer
