// import React from 'react'

const ScoreContainer = () => {
    return (
        <>
            <p className="nameInfo">10000</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">5</p>
            <p className="nameInfo">334</p>
            <p className="nameInfo">234</p>
            <p className="nameInfo">12</p>
            <p className="nameInfo">12</p>
        </>
    )
}

export default ScoreContainer
