// import React from 'react'

const NameContainer = ({names, isHidden}) => {

    return (
       
       <>
            <p className="nameInfo">{names[0]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{names[1]}</p>
            <p className="nameInfo">{names[2]}</p>
            <p className="nameInfo">{names[0]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{names[1]}</p>
            <p className="nameInfo">{names[2]}</p>
            
        </>
    )
}

export default NameContainer
