// import React from 'react'

const RankContainer = ({ranks}) => {
    return (
        <>
            <p className="nameInfo">{ranks[0]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{ranks[1]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{ranks[2]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{ranks[3]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{ranks[4]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{ranks[5]}</p> {/* This will be dynamically generated by server */}
        </>
    )
}

export default RankContainer
