// import React from 'react'

const ScoreContainer = ({scores}) => {
    return (
        <>
            <p className="nameInfo">{scores[0]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{scores[1]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{scores[2]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{scores[3]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{scores[4]}</p> {/* This will be dynamically generated by server */}
            <p className="nameInfo">{scores[5]}</p> {/* This will be dynamically generated by server */}
        
        </>
    )
}

export default ScoreContainer
